spring.application.name=inventory-service
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

eureka.client.service-url.defaultZone=http://eureka:eureka123@localhost:8761/eureka
eureka.instance.prefer-ip-address=true

resilience4j.bulkhead.instances.inventoryService.max-concurrent-calls=10
resilience4j.ratelimiter.instances.inventoryService.limit-for-period=10
resilience4j.ratelimiter.instances.inventoryService.limit-refresh-period=1s

management.endpoints.web.exposure.include=*
management.metrics.export.prometheus.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
